name: 'ci'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4

    - name: Set node version to 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - run: npm install

    - name: markdown lint
      run: npm run lint:md

    - name: js lint
      run: npm run lint:js

    - name: Run unit tests
      run: npm run test
